name: Destroy ECS stacks

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DESTROY_ECS to confirm"
        required: true

permissions:
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Guard (confirmation)
        run: |
          echo "confirm='${{ github.event.inputs.confirm }}'"
          if [ "${{ github.event.inputs.confirm }}" != "DESTROY_ECS" ]; then
            echo "‚ùå Confirmation failed. Type DESTROY_ECS exactly."
            exit 1
          fi

      - name: Configure AWS credentials (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete stacks (reverse order)
        run: |
          aws cloudformation delete-stack --stack-name EcsEc2Stack || true
          aws cloudformation wait stack-delete-complete --stack-name EcsEc2Stack || true

          aws cloudformation delete-stack --stack-name EcsFargateStack || true
          aws cloudformation wait stack-delete-complete --stack-name EcsFargateStack || true

          aws cloudformation delete-stack --stack-name EcrStack || true
          aws cloudformation wait stack-delete-complete --stack-name EcrStack || true

          aws cloudformation delete-stack --stack-name NetworkStack || true
          aws cloudformation wait stack-delete-complete --stack-name NetworkStack || true
